{% set name = "sdf" %}
{% set version = "0.3.6" %}
{% set sha256 = "da51cb64c411cfdd4bc335f6e29f004917005b4ae25c9220f21ce82a93ead10c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ScientificDataFormat/SDF-Python/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  # macOS: shasum -a 256 <file>
  # Windows: certutil -hashfile <file> SHA256

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - h5py
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - sdf
    - sdf.examples

about:
  home: https://github.com/ScientificDataFormat/SDF-Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: "Work with the Scientific Data Format in Python"

extra:
  recipe-maintainers:
    - t-sommer
