{% set name = "sdf" %}
{% set version = "0.3.4" %}
{% set sha256 = "5D931CD5D940EE2CD4BB7C3CFA094F3C54610EF106B252C07692DECB441E8B69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ScientificDataFormat/SDF-Python/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - h5py
    - matplotlib
    - numpy
    - scipy

test:
  imports:
    - sdf
    - sdf.examples

about:
  home: https://github.com/ScientificDataFormat/SDF-Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: "Work with the Scientific Data Format in Python"

extra:
  recipe-maintainers:
    - t-sommer
