travis:
  secure:
    BINSTAR_TOKEN: ICzjJ3wBPAJdLk1ftZNUBdd0IPg8sOJsLltpAppX4optW/3Rpi0TcOw/cuqFAzDqsGVD7Vu7DobaapI1QSKFB/SDDG9AyQRpB684nFvegzoXnbCLSU67gHf2qoHgCpYirUljJaMASwM8zotw/YBZyncFzDryT3Fepdmv9jHqDMo5f7RpXPejKUdjwiPfLz+QMSYyszXx9edrLlkIMw98y+BAhpUkPLZxU9UjHF0rg7L0J8++r46HhFo+mqXgspDPts3Y2LMS06ZMumUBG1AXPWg0sAZ+Qet3gK0oBQbtKA4y6mgorU/YRqf8knuemGKJJ2zLtVFkIwi8Sw9hFA6LniYsKI9sTrV0CH7Y2WdLpa1+1Ec7dZO4V7Os7Xl6JGwDpuE2F1hZi1jZgBCEy7TMjUEahXFVDST2juVTsn3rrkZUwHWcCusPeA14r7KygGuroIqpsbrHL03RegdLx5Eddqy1HqqKYn+NByQSq3EHO5QgFWV89ZuJ0rSxIf7HIB3UBSlGvEKsm/FdbR5X12Q7z/jy0RS5KmImDFvSw6AjfToifiUYSPMMhC3yZAzleLQulhdWt15giNzhAalKPsT5GGjWTkn3veq383yS8BIecXCzJtmkHF/a0LrcW592ichuBuSZffXwEuEJkiXBCk5569udULpcWpmMPDXav0oI/wQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
